// final url = 'http://192.168.87.229:3000/';
final url = 'http://192.168.1.108:3000/';
final registration = url + "registration";
final loginUrl = url + "login";
final createEvent = url + "createEvent";
final getEventList = url + "getEventList";
final delEvent = url + "deleteEvent";
final createClub = url + "createClub";
final getClub = url + "getClubList";
