// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvLasccnPH_4TgO6piuAMeMWptJcnGj0',
    appId: '1:377102217262:web:d9194849ce988f37c76fbf',
    messagingSenderId: '377102217262',
    projectId: 'bad-a-pow',
    authDomain: 'bad-a-pow.firebaseapp.com',
    storageBucket: 'bad-a-pow.appspot.com',
    measurementId: 'G-M2PF913QBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NDcwa4ZKpWQFGnPhHAwDHxnvpyFy6XY',
    appId: '1:377102217262:android:75ea9f513a42f5a8c76fbf',
    messagingSenderId: '377102217262',
    projectId: 'bad-a-pow',
    storageBucket: 'bad-a-pow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWNmAxKdd3pKEUf65tZgRHumQEeT9x3bo',
    appId: '1:377102217262:ios:2b9b26902e64a503c76fbf',
    messagingSenderId: '377102217262',
    projectId: 'bad-a-pow',
    storageBucket: 'bad-a-pow.appspot.com',
    iosBundleId: 'com.example.finalmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWNmAxKdd3pKEUf65tZgRHumQEeT9x3bo',
    appId: '1:377102217262:ios:bccc313a0175fb4fc76fbf',
    messagingSenderId: '377102217262',
    projectId: 'bad-a-pow',
    storageBucket: 'bad-a-pow.appspot.com',
    iosBundleId: 'com.example.finalmo.RunnerTests',
  );
}
